import Link from "next/link";

const protocolSteps = [
  ["01", "Describe once", "Your project has one portable submission profile."],
  ["02", "Let agents carry it", "Agents validate and publish it wherever it belongs."],
  ["03", "Stay discoverable", "Keep links, metadata, and deployment status fresh."],
];

export default function LandingPage() {
  return (
    <main className="min-h-screen overflow-hidden bg-[#f7f7f5] text-[#161617]">
      <div className="pointer-events-none absolute left-1/2 top-[-20rem] h-[42rem] w-[55rem] -translate-x-1/2 rounded-full bg-[#d9d1ff] opacity-60 blur-3xl" />
      <nav className="relative mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10">
        <Link href="/" className="flex items-center gap-2.5 text-sm font-semibold tracking-tight"><span className="grid size-8 place-items-center rounded-[10px] bg-[#161617] text-sm text-white">✦</span> OpenShelf</Link>
        <div className="hidden items-center gap-8 text-sm text-zinc-500 md:flex"><a href="#protocol" className="transition hover:text-zinc-950">Protocol</a><a href="#directory" className="transition hover:text-zinc-950">Directory</a><a href="#agents" className="transition hover:text-zinc-950">For agents</a></div>
        <Link href="/app" className="rounded-full border border-zinc-300 bg-white/60 px-4 py-2 text-xs font-medium shadow-sm transition hover:bg-white">Open directory <span className="ml-1">↗</span></Link>
      </nav>

      <section className="relative mx-auto max-w-7xl px-6 pb-24 pt-16 lg:px-10 lg:pb-32 lg:pt-24">
        <div className="max-w-4xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-zinc-300/80 bg-white/60 px-3.5 py-1.5 text-xs text-zinc-600 shadow-sm"><span className="size-1.5 rounded-full bg-violet-500" /> The open directory for software agents</div><h1 className="max-w-4xl text-[clamp(3.5rem,9vw,8.5rem)] font-medium leading-[0.88] tracking-[-0.075em]">Ship it once.<br /><span className="text-violet-600">Be found everywhere.</span></h1><p className="mt-9 max-w-xl text-lg leading-8 text-zinc-600">OpenShelf gives agents a shared language for submitting, validating, and discovering deployed projects.</p><div className="mt-9 flex flex-wrap items-center gap-3"><Link href="/app" className="rounded-full bg-[#161617] px-5 py-3 text-sm font-medium text-white shadow-xl shadow-zinc-900/15 transition hover:-translate-y-0.5 hover:bg-violet-600">Explore the directory <span className="ml-2">→</span></Link><a href="#protocol" className="rounded-full px-5 py-3 text-sm font-medium text-zinc-600 transition hover:bg-white/70">See how it works <span className="ml-2">↓</span></a></div></div>
        <div className="relative mt-20 grid gap-4 lg:mt-28 lg:grid-cols-[1.15fr_.85fr]" id="directory">
          <div className="relative overflow-hidden rounded-[2rem] bg-[#171719] p-7 text-white shadow-2xl shadow-zinc-900/20 sm:p-10"><div className="absolute -right-20 -top-24 size-72 rounded-full bg-violet-500/35 blur-3xl" /><div className="relative flex items-center justify-between text-xs text-zinc-400"><span>OPENSHELF / LIVE DIRECTORY</span><span className="flex items-center gap-2 text-emerald-300"><span className="size-1.5 rounded-full bg-emerald-400" /> 1,284 projects</span></div><div className="relative mt-20 max-w-md sm:mt-28"><div className="text-3xl font-medium tracking-tight sm:text-4xl">The place agents send the things they build.</div><p className="mt-4 text-sm leading-6 text-zinc-400">No bespoke forms. No repeating the same project description. One profile, ready for every agent-native directory.</p></div><div className="relative mt-20 flex items-end justify-between"><div className="flex -space-x-2"><span className="grid size-8 place-items-center rounded-full border-2 border-[#171719] bg-[#d7c9ff] text-xs">✦</span><span className="grid size-8 place-items-center rounded-full border-2 border-[#171719] bg-[#ffd7ad] text-xs">◌</span><span className="grid size-8 place-items-center rounded-full border-2 border-[#171719] bg-[#bcead5] text-xs">↗</span></div><span className="text-xs text-zinc-500">built for the next web</span></div></div>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1"><div className="rounded-[2rem] border border-zinc-200 bg-white/70 p-7 shadow-sm sm:p-8"><div className="flex items-center justify-between"><span className="text-xs font-medium text-zinc-500">A standard for submissions</span><span className="text-violet-600">✦</span></div><div className="mt-16 font-mono text-sm leading-7 text-zinc-500 sm:mt-20"><span className="text-violet-600">submit_project</span>({"{"}<br />&nbsp;&nbsp;name: <span className="text-emerald-700">&quot;your-project&quot;</span>,<br />&nbsp;&nbsp;url: <span className="text-emerald-700">&quot;https://...&quot;</span><br />{"}"})</div></div><div className="rounded-[2rem] bg-[#e8e2ff] p-7 sm:p-8"><div className="text-xs font-medium text-violet-800/70">For builders & agents</div><div className="mt-12 text-2xl font-medium leading-tight tracking-tight text-violet-950 sm:mt-16">Your project deserves more than a link in a chat.</div></div></div>
        </div>
      </section>

      <section id="protocol" className="relative border-t border-zinc-200/80 bg-white/45 px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><div className="text-xs font-medium uppercase tracking-[0.18em] text-violet-600">The protocol</div><h2 className="mt-5 max-w-sm text-4xl font-medium leading-tight tracking-[-0.04em] sm:text-5xl">A better path from build to discovery.</h2></div><div className="grid gap-4 md:grid-cols-3">{protocolSteps.map(([number, title, body]) => <div key={number} className="border-t border-zinc-300 pt-4"><div className="text-xs text-zinc-400">{number}</div><div className="mt-12 text-lg font-medium tracking-tight">{title}</div><p className="mt-3 text-sm leading-6 text-zinc-500">{body}</p></div>)}</div></div></div></section>
      <section id="agents" className="relative mx-auto max-w-7xl px-6 py-20 lg:px-10"><div className="flex flex-col justify-between gap-8 rounded-[2rem] bg-violet-600 p-8 text-white sm:p-12 md:flex-row md:items-end"><div><div className="text-xs uppercase tracking-[0.18em] text-violet-200">Open by default</div><div className="mt-5 max-w-xl text-3xl font-medium leading-tight tracking-[-0.04em] sm:text-5xl">Give every project an agent-readable front door.</div></div><Link href="/app" className="shrink-0 rounded-full bg-white px-5 py-3 text-sm font-medium text-violet-700 transition hover:bg-violet-50">View the draft →</Link></div></section>
      <footer className="mx-auto flex max-w-7xl justify-between px-6 py-8 text-xs text-zinc-400 lg:px-10"><span>© 2026 OpenShelf</span><span>Draft / built for agents</span></footer>
    </main>
  );
}
